const topCoins = {
    // Major coins
    'bitcoin': 'bitcoin',
    'btc': 'bitcoin',
    'ethereum': 'ethereum',
    'eth': 'ethereum',
    'tether': 'tether',
    'usdt': 'tether',
    'binance coin': 'binancecoin',
    'bnb': 'binancecoin',
    'usd coin': 'usd-coin',
    'usdc': 'usd-coin',
    'xrp': 'ripple',
    'ripple': 'ripple',
    'cardano': 'cardano',
    'ada': 'cardano',
    'solana': 'solana',
    'sol': 'solana',
    'dogecoin': 'dogecoin',
    'doge': 'dogecoin',
    'sui': 'sui',
    'sui network': 'sui',
    
    // Other top coins
    'polkadot': 'polkadot',
    'dot': 'polkadot',
    'polygon': 'matic-network',
    'matic': 'matic-network',
    'litecoin': 'litecoin',
    'ltc': 'litecoin',
    'tron': 'tron',
    'trx': 'tron',
    'shiba inu': 'shiba-inu',
    'shib': 'shiba-inu',
    'dai': 'dai',
    'avalanche': 'avalanche-2',
    'avax': 'avalanche-2',
    'wrapped bitcoin': 'wrapped-bitcoin',
    'wbtc': 'wrapped-bitcoin',
    'uniswap': 'uniswap',
    'uni': 'uniswap',
    'chainlink': 'chainlink',
    'link': 'chainlink',
    'cosmos': 'cosmos',
    'atom': 'cosmos',
    'leo token': 'leo-token',
    'leo': 'leo-token',
    'monero': 'monero',
    'xmr': 'monero',
    'stellar': 'stellar',
    'xlm': 'stellar',
    'bitcoin cash': 'bitcoin-cash',
    'bch': 'bitcoin-cash',
    'ethereum classic': 'ethereum-classic',
    'etc': 'ethereum-classic',
    'filecoin': 'filecoin',
    'fil': 'filecoin',
    'hedera': 'hedera-hashgraph',
    'hbar': 'hedera-hashgraph',
    'apecoin': 'apecoin',
    'ape': 'apecoin',
    'near protocol': 'near',
    'near': 'near',
    'vechain': 'vechain',
    'vet': 'vechain',
    'quant': 'quant-network',
    'qnt': 'quant-network',
    'algorand': 'algorand',
    'algo': 'algorand',
    'fantom': 'fantom',
    'ftm': 'fantom',
    'aave': 'aave',
    'maker': 'maker',
    'mkr': 'maker',
    'frax': 'frax',
    'the graph': 'the-graph',
    'grt': 'the-graph',
    'eos': 'eos',
    'decentraland': 'decentraland',
    'mana': 'decentraland',
    'theta': 'theta-token',
    'axie infinity': 'axie-infinity',
    'axs': 'axie-infinity',
    'tezos': 'tezos',
    'xtz': 'tezos',
    'elrond': 'elrond-erd-2',
    'egld': 'elrond-erd-2',
    'the sandbox': 'the-sandbox',
    'sand': 'the-sandbox',
    'pancakeswap': 'pancakeswap-token',
    'cake': 'pancakeswap-token',
    'flow': 'flow',
    'kucoin token': 'kucoin-shares',
    'kcs': 'kucoin-shares',
    'iota': 'iota',
    'miota': 'iota',
    'neo': 'neo',
    'trust wallet token': 'trust-wallet-token',
    'twt': 'trust-wallet-token',
    'synthetix': 'havven',
    'snx': 'havven',
    'osmosis': 'osmosis',
    'osmo': 'osmosis',
    'compound': 'compound-governance-token',
    'comp': 'compound-governance-token',
    'chiliz': 'chiliz',
    'chz': 'chiliz',
    'bitcoin sv': 'bitcoin-cash-sv',
    'bsv': 'bitcoin-cash-sv',
    'arweave': 'arweave',
    'ar': 'arweave',
    'dash': 'dash',
    'zilliqa': 'zilliqa',
    'zil': 'zilliqa',
    'huobi token': 'huobi-token',
    'ht': 'huobi-token',
    'zcash': 'zcash',
    'zec': 'zcash',
    'gatetoken': 'gatechain-token',
    'gt': 'gatechain-token',
    'thorchain': 'thorchain',
    'rune': 'thorchain',
    'kava': 'kava',
    'gala': 'gala',
    'basic attention token': 'basic-attention-token',
    'bat': 'basic-attention-token',
    'enjin coin': 'enjincoin',
    'enj': 'enjincoin',
    'loopring': 'loopring',
    'lrc': 'loopring',
    '1inch': '1inch',
    'sushi': 'sushi',
    'convex finance': 'convex-finance',
    'cvx': 'convex-finance',
    'waves': 'waves',
    'curve dao token': 'curve-dao-token',
    'crv': 'curve-dao-token',
    'celo': 'celo',
    'kusama': 'kusama',
    'ksm': 'kusama',
    'harmony': 'harmony',
    'one': 'harmony',
    'bitcoin gold': 'bitcoin-gold',
    'btg': 'bitcoin-gold',
    'dydx': 'dydx',
    'render token': 'render-token',
    'rndr': 'render-token',
    'nexo': 'nexo',
    'celsius': 'celsius-degree-token',
    'cel': 'celsius-degree-token',
    'gnosis': 'gnosis',
    'gno': 'gnosis',
    'kyber network': 'kyber-network-crystal',
    'knc': 'kyber-network-crystal',
    'amp': 'amp-token',
    'decred': 'decred',
    'dcr': 'decred',
    'nem': 'nem',
    'xem': 'nem',
    'mina': 'mina-protocol',
    'qtum': 'qtum',
    'icon': 'icon',
    'icx': 'icon',
    'ravencoin': 'ravencoin',
    'rvn': 'ravencoin',
    'secret': 'secret',
    'scrt': 'secret',
    
    // DeFi tokens
    'yearn.finance': 'yearn-finance',
    'yfi': 'yearn-finance',
    'balancer': 'balancer',
    'bal': 'balancer',
    'terra': 'terra-luna',
    'luna': 'terra-luna',
    
    // NFT and Gaming tokens
    'stepn': 'stepn',
    'gmt': 'stepn',
    'immutable x': 'immutable-x',
    'imx': 'immutable-x',
    'illuvium': 'illuvium',
    'ilv': 'illuvium',
    'gods unchained': 'gods-unchained',
    'gods': 'gods-unchained',
    
    // Exchange tokens
    'ftx token': 'ftx-token',
    'ftt': 'ftx-token',
    'crypto.com coin': 'crypto-com-chain',
    'cro': 'crypto-com-chain',
    'okb': 'okb',
    
    // Stablecoins
    'binance usd': 'binance-usd',
    'busd': 'binance-usd',
    'true usd': 'true-usd',
    'tusd': 'true-usd',
    'paxos standard': 'paxos-standard',
    'pax': 'paxos-standard',
    'neutrino usd': 'neutrino',
    'usdn': 'neutrino',
    'gemini dollar': 'gemini-dollar',
    'gusd': 'gemini-dollar',
    
    // Layer 2 solutions
    'optimism': 'optimism',
    'op': 'optimism',
    'arbitrum': 'arbitrum',
    'arb': 'arbitrum',
    
    // Web3 Coins
    'helium': 'helium',
    'hnt': 'helium',
    'internet computer': 'internet-computer',
    'icp': 'internet-computer',
    'theta fuel': 'theta-fuel',
    'tfuel': 'theta-fuel',
    'ankr': 'ankr',
    'livepeer': 'livepeer',
    'lpt': 'livepeer',
    'storj': 'storj',
    'siacoin': 'siacoin',
    'sc': 'siacoin',
    
    // Metaverse tokens
    'wax': 'wax',
    'waxp': 'wax',
    'phantasma': 'phantasma',
    'soul': 'phantasma',
    'ultra': 'ultra',
    'uos': 'ultra',
    
    // Privacy coins
    'horizen': 'zencash',
    'zen': 'zencash',
    'verge': 'verge',
    'xvg': 'verge'
};